"""
Project Configuration
Brain Tumor Multimodal Analysis — NLP Module (TextBraTS)

Mirrors the structure of cv_module/config.py so both modules can be
imported side by side by the fusion module with a consistent pattern.

Author:
Nour Hossam
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Tuple


@dataclass(frozen=True)
class Config:
    """
    Global configuration used across the NLP module.

    Note: this class is used purely as a namespace (Config.X), never
    instantiated as Config(), so every field below is fully type
    annotated to be a real dataclass field — unlike a plain class,
    this means `python -c "from nlp_module.config import Config;
    print(Config())"` would also work correctly if ever needed.
    """

    # ==========================================================
    # Dataset — Raw TextBraTS reports
    # ==========================================================

    DATASET_DIR: Path = Path(
        "datasets/raw/textbrats/TextBraTSData"
    )

    # Same dataset_split.json produced by the CV module's Notebook 03.5.
    # The NLP split is NOT independent — it is derived from this file
    # (Notebook 03 — apply-cv-split-to-textbrats) so that train/validation/
    # test patient membership is identical across both modalities. This
    # is required for the fusion module: a patient must never be "train"
    # in one modality and "test" in the other.
    SPLIT_FILE: Path = Path(
        "datasets/splits/dataset_split.json"
    )

    # ==========================================================
    # Dataset — Processed reports (.csv)
    #
    # Generated by Notebook 03 (split) → Notebook 04 (cleaning).
    # Structure:
    #   datasets/processed/nlp/
    #       train_reports_clean.csv
    #       validation_reports_clean.csv
    #       test_reports_clean.csv
    # Columns: patient_id, report, clean_report, words, characters
    # ==========================================================

    PROCESSED_REPORTS_DIR: Path = Path(
        "datasets/processed/nlp"
    )

    # ==========================================================
    # Dataset — Extracted embeddings (.npy)
    #
    # Generated by Notebook 06a / 06b (contextual embedding extraction).
    # Structure:
    #   datasets/processed/nlp/<model_folder>/
    #       train_embeddings.npy       (N_train, 768)
    #       validation_embeddings.npy  (N_val,   768)
    #       test_embeddings.npy        (N_test,  768)
    #       train_metadata.csv         patient_id, in the SAME row order
    #       validation_metadata.csv    as the corresponding .npy file
    #       test_metadata.csv
    #
    # ⚠️ Row order in the .npy files matches row order in the matching
    # metadata.csv, NOT necessarily the CV module's .pt file order.
    # Always join on patient_id when combining with image features —
    # never assume positional alignment across modalities.
    # ==========================================================

    EMBEDDINGS_DIR: Path = Path(
        "datasets/processed/nlp"
    )

    # ==========================================================
    # Randomness
    # ==========================================================

    SEED: int = 42

    # ==========================================================
    # Text Cleaning
    # ==========================================================

    # Whitespace/newline/tab normalization only (Notebook 04) — no
    # lowercasing, no stopword removal, no stemming. BioBERT/ClinicalBERT
    # tokenizers are cased and trained on raw clinical text, so aggressive
    # cleaning would discard information the model was pretrained to use.

    # ==========================================================
    # Tokenization / Model
    # ==========================================================

    # Both candidate encoders evaluated in Notebooks 05a/05b/06a/06b/07.
    # Embedding-statistics alone did not separate them (Notebook 07:
    # cosine similarity ≈ 0.92 between the two) — final choice is
    # deferred to downstream fusion performance, so both folders are
    # kept on disk and MODEL_NAME just selects which one this module
    # currently points to by default.
    MODEL_NAME: str = "dmis-lab/biobert-base-cased-v1.1"

    AVAILABLE_MODELS: Tuple[str, ...] = (
        "dmis-lab/biobert-base-cased-v1.1",
        "emilyalsentzer/Bio_ClinicalBERT",
    )

    # 99th percentile token length across train+val+test was well under
    # this limit in both tokenizer analyses (Notebooks 05a/05b); reports
    # longer than this are truncated. See Notebook 05a §7 for the full
    # truncation-vs-length tradeoff table.
    MAX_LENGTH: int = 256

    # ==========================================================
    # Embedding Output
    # ==========================================================

    EMBEDDING_DIM: int = 768

    # ==========================================================
    # Saving
    # ==========================================================

    LOG_DIR: Path = Path("logs")

    RESULT_DIR: Path = Path("reports/nlp/results")

    FIGURE_DIR: Path = Path("reports/nlp/figures")
