"""
Project Configuration
Brain Tumor Segmentation (BraTS2020)
"""

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Config:
    """
    Global configuration used across the CV module.
    """

    # ==========================================================
    # Dataset — Raw NIfTI
    # ==========================================================

    DATASET_PATH = Path(
        "datasets/raw/brats2020"
    )

    SPLIT_FILE = Path(
        "datasets/splits/dataset_split.json"
    )

    # ==========================================================
    # Dataset — Preprocessed .pt
    #
    # Generated by Notebook 06.5 (preprocessed dataset serialization).
    # Structure:
    #   datasets/processed/cv/
    #       train/       BraTS20_Training_001.pt ...
    #       validation/  BraTS20_Training_002.pt ...
    #       test/        BraTS20_Training_003.pt ...
    #       index.json
    # ==========================================================

    PROCESSED_PATH = Path(
        "datasets/processed/cv"
    )

    # ==========================================================
    # Dataset Caching
    # ==========================================================

    CACHE_RATE = 1.0

    # ==========================================================
    # Randomness
    # ==========================================================

    SEED: int = 42

    # ==========================================================
    # MRI
    # ==========================================================

    MODALITIES = (
        "flair",
        "t1",
        "t1ce",
        "t2"
    )

    # ==========================================================
    # Labels
    # ==========================================================

    ORIGINAL_LABELS = (0, 1, 2, 4)

    TARGET_LABELS = (0, 1, 2, 3)

    # ==========================================================
    # Preprocessing
    # ==========================================================

    ROI_SIZE = (128, 128, 128)

    CROP_MARGIN = 5

    POS_RATIO = 1

    NEG_RATIO = 1

    NUM_SAMPLES = 2

    # ==========================================================
    # Training
    # ==========================================================

    TRAIN_BATCH_SIZE = 2

    VALIDATION_BATCH_SIZE = 1

    TEST_BATCH_SIZE = 1

    NUM_WORKERS = 2

    PIN_MEMORY = True

    SHUFFLE = True

    # ==========================================================
    # Training Hyperparameters
    # ==========================================================

    NUM_EPOCHS = 300

    LEARNING_RATE = 1e-4

    WEIGHT_DECAY = 1e-5

    # ==========================================================
    # Model
    # ==========================================================

    IN_CHANNELS = 4

    OUT_CHANNELS = 4

    # ==========================================================
    # SegResNet
    # ==========================================================

    INIT_FILTERS: int = 32

    DROPOUT_PROB: float = 0.2

    BLOCKS_DOWN = (1, 2, 2, 4)

    BLOCKS_UP = (1, 1, 1)

    # ==========================================================
    # Loss
    # ==========================================================

    SMOOTH_NR: float = 1e-5

    SMOOTH_DR: float = 1e-5

    SQUARED_PRED: bool = True

    # ==========================================================
    # Metrics
    # ==========================================================

    INCLUDE_BACKGROUND = False

    METRIC_REDUCTION = "mean"

    # ==========================================================
    # Saving
    # ==========================================================

    CHECKPOINT_DIR = Path(
        "models/segmentation"
    )

    LOG_DIR = Path(
        "logs"
    )

    FIGURE_DIR = Path(
        "reports/figures"
    )

    RESULT_DIR = Path(
        "reports/results"
    )
