"""Medical disclaimer for AI-generated outputs."""

from __future__ import annotations

import streamlit as st

MEDICAL_DISCLAIMER = (
    "This output is generated by an AI clinical decision support system and "
    "should assist—not replace—professional medical judgment."
)


def render_disclaimer(container=None) -> None:
    target = container or st
    target.info(MEDICAL_DISCLAIMER)
